### PR TITLE
Homepage

### LINKED ISSUE #12: Home Page - Top half

### PR DESCRIPTION
**Pull request by BoxedFruits**
Create the homepage 

This will close 

#12 
#11 
#5

### CODE REVIEW

**Comment by Nizzle88** [comment]
Looking pretty sweet.

The page is missing the GIF playing behind the text, as well as the navigation arrows mentioned in [#5](https://github.com/BoxedFruits/KaijuKata/issues/5)

Also the alignment and spacing is a little off for the footer.
  
- You can remove the margin on the <p> to center "Not affiliated with KaijuKingz or Augminted Labs"
- Copy the <div> that surrounds the anchor elements and add 3 anchors to each div to fix text alignment in mobile view

**Comment by BoxedFruits** [comment]
> Copy the
that surrounds the anchor elements and add 3 anchors to each div to fix text alignment in mobile view

Could you clarify what you mean by this? I see that it stacks weird between smaller and medium break points but unsure how it should stack.

Example at 607x791 screen size
image

**Comment by Nizzle88** [comment]
Not sure what happened to my comment there. 

It was supposed to say to split the container div for the anchor tags into 2 and use flex-col on sm devices. 

I've pushed a commit with the changes

**Comment by BoxedFruits** [comment]
I refactored it a little to save us from the extra div. Let me know if it looks good to you and we can get this merged

**Review by Nizzle88 — APPROVED** [review]

**Pull request merged**
